### PR TITLE
Saforem2 patch 1

### PR DESCRIPTION
**Pull request by saforem2**

### CODE REVIEW

**Comment by saforem2** [comment]
ope, didn't mean to do that

**Comment by MNoichl** [comment]
No worries! Are you planning on merging things later?

**Comment by saforem2** [comment]
Yeah I was going to work a bit on cleaning things up and make sure I didn't break anything of yours by removing the `{setup.cfg,setup.py}` but was planning to submit a PR shortly!

**Comment by MNoichl** [comment]
Sweet, clean-up is much appreciated! 
I'm not quite sure what was going on there exactly, but some of the setup files might have been necessary for the GitHub action to update the package on PyPi to work - ?  Initially, I had tried to set it up just with a toml.

**Pull request closed without merging**
